io_uring: fix build error, implicit declaration
When building io_uring.c we see the following build error:

../fs/io_uring.c: In function 'loop_rw_iter':
../fs/io_uring.c:1628:21: error: implicit declaration of function 'kmap'; did you mean 'vmap'? [-Werror=implicit-function-declaration]
    iovec.iov_base = kmap(iter->bvec->bv_page)
                     ^~~~
                     vmap
../fs/io_uring.c:1628:19: warning: assignment to 'void *' from 'size_t' {aka 'long unsigned int'} makes pointer from integer without a cast [-Wint-conversion]
    iovec.iov_base = kmap(iter->bvec->bv_page)
                   ^
../fs/io_uring.c:1643:4: error: implicit declaration of function 'kunmap'; did you mean 'vunmap'? [-Werror=implicit-function-declaration]
    kunmap(iter->bvec->bv_page);
    ^~~~~~
    vunmap

Rework the to include linux/highmem.h.

Fixes: 311ae9e159d8 ("io_uring: fix dead-hung for non-iter fixed rw")
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>